version: '3.6'

services:

  redis:
    image: redis:6-alpine
    env_file: .env
    command: redis-server --appendonly yes
    healthcheck:
      test: redis-cli ping
    volumes:
      - redis:/data
    ports:
      - 6379:6379
    restart: on-failure

  postgres:
    image: postgres:12-alpine
    env_file: .env
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - 5432:5432
    restart: on-failure

volumes:
  redis:
  postgres:
